- name: People microservice
  be-technology: .NET 6.0, C#, ASP.NET Core Web API, Entity Framework
  fe-technology: ASP.NET Core, Single Page Application, React
  other-technology: SQL Server, Docker, OpenAPI (Swagger), Visual Studio, Postman
  documentation: wiki/spaces/SK/pages/33048/People+microservice
  description: The people microservice is in charge of managing the personal information like the contact info, addresses, birthday, avatar, etc.
  demo: projectpeople.gif
  repository: speedkt-people-api
- name: Knowledge microservice
  be-technology: node.js, ReactJS, mongoDB
  fe-technology: 
  other-technology:
  documentation: wiki/spaces/SK/pages/33048/Knowledge+microservice
  description: Microservice that is used to manage the knowledge information
  demo: projecttool.gif
  repository: speedkt-knowledge-api