- name: People microservice
  be-technology: .NET 6.0, C#, ASP.NET Core Web API, Entity Framework
  fe-technology: React, JavaScript
  other-technology: SQL Server
  tool: Visual Studio 2022, Docker, Postman, OpenAPI (Swagger)
  documentation: wiki/spaces/SK/pages/33048/People+microservice
  description: The people microservice is in charge of managing the personal information like the contact info, addresses, birthday, avatar, etc.
  demo: projectpeople.gif
  repositoryApi: speedkt-people-api
  repositoryWeb: speedkt-people-web
- name: Knowledge microservice
  be-technology: node.js, ReactJS, mongoDB
  fe-technology: 
  other-technology:
  tool:
  documentation: wiki/spaces/SK/pages/33048/Knowledge+microservice
  description: Microservice that is used to manage the knowledge information
  demo: projecttool.gif
  repositoryApi: speedkt-knowledge-api
  repositoryWeb: speedkt-knowledge-web